# 端口号
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat2db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # 配置自带数据库的相对路径
#    url: jdbc:h2:~/.chat2db/db/chat2db_dev;MODE=MYSQL
#    driver-class-name: org.h2.Driver
  mysql:
    console:
      enabled: true
      path: /mysql
      settings:
        trace: true
        web-allow-others: true
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        trace: true
#        web-allow-others: true
server:
  port: 10821

chat2db:
  gateway:
    base-url: http://test.sqlgpt.cn/gateway
    model-base-url: http://test.sqlgpt.cn/gateway
management:
  endpoints:
    web:
      exposure:
        include: startup
